import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center'
    },
    titleBox: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginLeft: '7.5%',
        marginRight: '7.5%',
        position: 'relative',
        height: 29,
        marginTop:69,
    },
    title: {
        display: 'flex',
        position:'relative',
        fontFamily: 'Gotham',
        fontStyle: 'normal',
        fontWeight: '700',
        fontSize: 24,
        lineHeight: 29,
        color: '#000000',
    },
    searchBox: {
        display: 'flex',
        padding: 16,
        position: 'relative',
        flexDirection: 'column',
        width: '85%',
        height: 247,
        left: '7.5%',
        marginTop: 24,
        backgroundColor: '#FFFFFF',
        shadowColor: 'rgba(0, 0, 0, 0.25)',
        shadowOpacity: 8,
        borderRadius: 16,
    },
    searchText: {
        position: 'relative',
        fontFamily: 'Gotham',
        fontStyle: 'normal',
        fontWeight: '700',
        fontSize: 18,
        lineHeight: 22,
        color: '#000000',
    },
    input: {
        alignItems: 'flex-start',
        padding: 15,
        position: 'relative',
        height: 50,
        marginTop: 16,
        backgroundColor: '#FFFFFF',
        borderColor: '#5AC8FA',
        borderRadius: 10,
        borderWidth: 1,
    },
    inpContainer: {
        display: 'flex',
        position: 'relative',
        justifyContent: 'center',
        marginTop: 16,
        flexDirection: 'row', 
        justifyContent: 'space-between'
    },
    input2: {
        display: 'flex',
        padding: 10,
        position: 'relative',
        alignItems: 'center',
        width: 140,
        height: 50,
        backgroundColor: '#FFFFFF',
        borderColor: '#5AC8FA',
        borderRadius: 10,
        borderWidth: 1,        
    },
    button:{
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 7,
        position: 'relative',
        width: '100%',
        height: 45,
        marginTop: 16,
        backgroundColor: '#5AC8FA',
        shadowColor: 'rgba(0, 0, 0, 0.15)',
        shadowOpacity: 2,
        borderRadius: 10,    
    },
    btnTitle: {
        fontFamily: 'Gotham',
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: 16,
        lineHeight: 20,
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        color: '#FFFFFF',
    },
    infoBox: {
        flex: 1,
        display: 'flex',
        position: 'relative',
        width: '85%',
        left: '7.5%',
    },
    header: {
        display: 'flex',
        position: 'relative',
        fontFamily: 'Gotham',
        fontStyle: 'normal',
        fontWeight: '700',
        fontSize: 18,
        marginTop: 24,
        lineHeight: 22,
        color: '#000000',
    },
    cardBox: {
        display: 'flex',
        flexDirection: 'column',
        position: 'relative',
        width: '100%',
        height: 127,
        marginBottom: 16,
        padding: 16,
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
    },
    headBox: {
        display: 'flex',
        flexDirection: 'row', 
        position: 'relative',
        width: '100%',
        justifyContent: 'space-between',
        marginRight: 16,
    },
    image: {
        width: 57, 
        height: 57,
        position: 'relative',
        marginRight: 12,
    },
    nameBox: {
        display: 'flex',
        flexDirection: 'row',
        position: 'relative',
        justifyContent: 'space-between',
    },
    hotelName: {
        position: 'relative',
        fontFamily: 'Gotham',
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: 16,
        width: 206,
        letterSpacing: -0.408,
        lineHeight: 22,
        color: '#000000',
    },
    ratingBox:{
        display: 'flex',
        flexDirection: 'row',
        position: 'relative',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    rooms: {
        position: 'relative',
        fontFamily: 'Gotham',
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: 13,
        lineHeight: 22,
        letterSpacing: -0.408,
        color: '#878787',
    },
    line:{
        display: 'flex',
        position: 'relative',
        alignItems: 'center',
        marginTop: 8,
        width: '100%',
        height: 0,
        borderColor: '#F4F4F4',
        borderWidth: 1,
    },
    costBox:{
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        marginTop: 8.5,
        lineHeight: 22,
        position: 'relative',
    },
    cost: {
        display: 'flex',
        position: 'relative',
        fontFamily: 'Gotham',
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: 13,
        letterSpacing: -0.408,
        color: '#878787',
    },
    price: {
        display: 'flex',
        position: 'relative',
        fontFamily: 'Gotham',
        fontWeight: '400',
        textAlign: 'right',
        justifyContent: 'flex-end',
        fontSize: 17,
        width: 74,
        letterSpacing: -0.408,       
        color: '#000000',
    },
    cardOverLay: {
        width: '100%',
        alignItems: 'center',
        top: -16,
        height: 127,
        backgroundColor: '#FFFFFF',
        position: 'absolute', 
        zIndex: 1,
        borderRadius: 16,
    },
    searchingBox: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-end',
        alignItems: 'center',
        padding: 16,
        position: 'relative',
        width: '100%',
        borderBottomLeftRadius: 16,
        borderBottomRightRadius: 16,
        height: 169,
        backgroundColor: '#FFFFFF',
    },
    searchInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingLeft: 47,       
        position: 'relative',
        width: 320,
        height: 50,
        backgroundColor: '#FFFFFF',
        borderColor: '#5AC8FA',
        borderWidth: 1, 
        borderRadius: 10,
        fontFamily: 'Gotham',
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: 14,
        lineHeight: 20,
    },
    searchTxt:{
        position: 'relative',
        width: 97,
        height: 21,
        fontFamily: 'Gotham',
        fontWeight: '400',
        fontSize: 14,
        lineHeight: 22,
        marginTop: 24,
        letterSpacing: -0.408,
        color: '#000000',
    },
    tabLine: {
        position: 'relative',
        justifyContent: 'space-between',
        width: 133,
        height: 3,
        backgroundColor: '#5AC8FA',
        borderRadius: 2,
    },
    menue: {
        flexDirection: 'row',
        position: 'relative',
        justifyContent: 'space-around',
        marginTop: 24, 
        width: '100%',
    },
    fav: {
        flexDirection: 'row',
        position: 'relative',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 16,
    },
    top:{
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'relative',
        width: 95,
        height: 28,
        backgroundColor: '#5AC8FA',
        borderRadius: 10,
    },
    textFilter:{
        fontFamily: 'Gotham',
        fontWeight: '400',
        fontSize: 14,
        lineHeight: 20,
        letterSpacing: -0.408,
    },
    costFilter:{
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'relative',
        width: 73,
        height: 28,
        marginLeft: 8,
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
    }
})