import { Dimensions, StyleSheet } from "react-native";


export const styles = StyleSheet.create({
    container: {
        width: '100%',
        height: '100%',
    },
    box:{
        width: '100%',
        height: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'relative',
        backgroundColor: 'linear-gradient(0deg, rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5))',
    },
    wrapper: {
        position: 'absolute',      
        alignItems: 'center',
        justifyContent: 'center',
        top: 228,
    },
    header1: {
        position: 'absolute',
        width: 195,
        left: '10%',
        top: 141,
        fontFamily: 'Gotham',
        fontStyle: 'normal',
        fontWeight: "400",
        fontSize: 16,
        lineHeight: 22,
        color: '#FFFFFF',
    },
    header2: {
        position: 'absolute',
        width: 239,
        height: 29,
        left: '10%',
        top: 167,
        fontFamily: 'Gotham',
        fontStyle: 'normal',
        fontWeight: "700", 
        fontSize: 24,
        lineHeight: 29,
        color: '#FFFFFF',   
    },
    input: {
        width: 343,
        height: 50,
        alignSelf: 'center',
        marginBottom: 16,
        backgroundColor: 'white',
        borderRadius: 10,
        fontFamily: 'Gotham',
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: 14,
        padding: 15,
    },
    wronInput:{
        width:343,
        height: 50,
        marginBottom: 16,
        backgroundColor: 'white',
        borderRadius: 10,
        borderColor: '#FF3B30',
        borderWidth: 1,
        fontFamily: 'Gotham',
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: 14,
        padding: 15,
    },
    wron: {
        left: '-8%',
        top: -8,
        bottom: 0,
        fontFamily: 'AGK',
        fontWeight: '400',
        fontSize: 12,
        lineHeight: 14,
        color: '#FFFFFF',
    },
    button: {
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 8,
        width: 343,
        height: 50,
        backgroundColor: '#5AC8FA',
        shadowColor: 'rgba(0, 0, 0, 0.25)',
        shadowOpacity: 2,
        borderRadius: 10,
        padding: 15,
    },
    btnTitle:{
        fontFamily: 'Gotham',
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: 16,
        lineHeight: 20,
        color: 'white',
    },
    image: {
        width: '100%',
        height: '100%',
        justifyContent: "center"
    },
})
