const hotels = [
    {
        id: '1',
        name: 'Silver Hotel &SPA',
        location: 'Green street, Central district',
        price: 120,
        image: require('../images/hotelIcon.png'),
        details: 'lalalalalalalalalallalal',
        rooms: 5, 
        incl: 'завтрак',
        roomimg: {uri:'https://traveltimes.ru/wp-content/uploads/2021/11/k2_galleries_1343_w-hotels-boston8.jpg'},
    },
    {
        id: '2',
        name: 'SPA',
        location: 'Green street',
        price: 50,
        image: require('../images/hotelIcon.png'),
        details: 'lalalalalal2222222alalalallalal',
        rooms: 1,
        incl: 'тренажеры',
        roomimg: {uri: 'https://travelata-a.akamaihd.net/thumbs/1920x1080/upload/2018_28/content_hotel_5b47bfa9c8d192.81416970.jpg'},
    },
    {
        id: '3',
        name: 'Sil5555ver Hotel &SPA',
        location: 'Green gggggstreet, Central district',
        price: 3000,
        image: require('../images/hotelIcon.png'),
        details: 'lalalalalalaggggggglalalallalal',
        rooms: 3,
        incl: 'завтрак',
        roomimg: {uri: 'https://greece.platinumclub.ru/cd/original_img/10736.jpg'},
    },
    {
        id: '4',
        name: 'Silver ggggggHotel &SPA',
        location: 'Green street, Centhhhhhhral district',
        price: 1200,
        image: require('../images/hotelIcon.png'),
        details: 'lalalalalalamjdsrhg 556s  d lalalallalal',
        rooms: 10,
        incl: 'завтрак',
        roomimg: {uri: 'https://s01.cdn-pegast.net/get/ad/7f/b2/2caa2db0ece6b4d96ef290bd8b8c4c6cd84967e86c2d7a042a3b05707e/5c3e02fd91c5a.png'},
    },
    {
        id: '5',
        name: 'Silver Hotel &SPA',
        location: 'Green street, Central district',
        price: 120,
        image: require('../images/hotelIcon.png'),
        details: 'lalalalalalalalalallalal',
        rooms: 5,
        incl: 'бассейн',
        roomimg: {uri: 'https://littletravel.ru/wp-content/uploads/2019/07/60743528.jpg'},
    },
    {
        id: '6',
        name: 'SPA',
        location: 'Green street',
        price: 50,
        image: require('../images/hotelIcon.png'),
        details: 'lalalalalal2222222alalalallalal',
        rooms: 1,
        incl: 'завтрак',
        roomimg: {uri: 'https://i.pinimg.com/originals/77/f6/ad/77f6ad124f775e70802a78f5c8b681d5.jpg'},
    },
    
]

export default hotels;